name: uas_mobile_programming

description: "A new Flutter project."

publish_to: 'none' # Private package, tidak untuk dipublish

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.0
  flutter_pdfview: ^1.3.1 
  path_provider: ^2.1.2 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/avatar.png
    - assets/images/logo_unpam.png
    - assets/pdfs/materi1.pdf
    - assets/pdfs/materi2.pdf
    - assets/pdfs/materi3.pdf
    - assets/pdfs/materi4.pdf
    - assets/pdfs/materi5.pdf
    - assets/pdfs/materi6.pdf
    - assets/pdfs/materi7.pdf
    - assets/pdfs/materi8.pdf
    - assets/pdfs/materi9.pdf
    - assets/pdfs/materi10.pdf
    - assets/pdfs/materi11.pdf
    - assets/pdfs/materi12.pdf
    - assets/pdfs/materi13.pdf
    - assets/pdfs/materi14.pdf
    # - assets/images/foto_profil.jpg  # Aktifkan jika kamu punya file ini

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo_unpam.png
  android: true
  ios: false
  fullscreen: true
